# Generated by Django 4.2.9 on 2024-02-09 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 9, 18, 56, 43, 574764, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
