# Generated by Django 5.0.3 on 2024-04-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_registeredevent_username_registeredevent_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredevent',
            name='user',
        ),
        migrations.AddField(
            model_name='registeredevent',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
