# Generated by Django 4.2.9 on 2024-02-10 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_customusermodel_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeredevent',
            old_name='event',
            new_name='event_name',
        ),
    ]
