# Generated by Django 4.2.9 on 2024-02-20 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_registeredevent_user_registeredevent_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredevent',
            name='Time',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
