# Generated by Django 4.2.9 on 2024-02-10 07:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_datetime_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='another_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
