# Generated by Django 4.2.9 on 2024-02-20 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_registeredevent_time_event_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='endtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
