# Generated by Django 4.2.9 on 2024-02-23 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_subevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredevent',
            name='sub_event_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
