# Generated by Django 4.2.9 on 2024-02-23 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_registeredevent_sub_event_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredevent',
            name='time',
        ),
    ]
