# Generated by Django 4.2.9 on 2024-03-25 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_registeredevent_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='subevent',
            name='end_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='subevent',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
