# Generated by Django 4.2.9 on 2024-03-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_remove_subevent_end_time_remove_subevent_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subevent',
            name='space_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
